modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="rpg_craft"
version="1.0.0"
displayName="Rpg craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Stremote, MCreator"

[[dependencies.rpg_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




